---
platform: linux
image_resource:
 type: docker-image
 # we could use a smaller image
 source:
   repository: cfcontainerization/go-tools
   tag: latest
inputs:
- name: src
  path: src/code.cloudfoundry.org/cf-operator
- name: ci
outputs:
- name: helm-charts
run:
  path: ci/pipelines/cf-operator/tasks/build-helm.sh
