---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: havener/build-environment
    tag: latest
inputs:
- name: ci
- name: docker
params:
  repository:
  candidate_repository:
  username:
  password:
run:
  path: ci/pipelines/cf-operator/tasks/publish.sh
